### ISSUE TITLE
NetStandard Target

### ISSUE THREAD

**Issue by waynebrantley** [Domysee/Pather.CSharp#1]
Good library.  Works great.

However, this is one small issue.
When I have a solution that targets .NET Standard 1.4 and I add your package, it adds a reference to ``System.Runtime.InteropServices`` version 4.3.   When I compile I get the 'found conflicts between two different versions'.  This is caused by your library combined with the the above reference.

If I change my target to .NET Standard 1.6, the warnings go away.

I think the issue is you have targeted .NET Standard 1.0, PLUS a package from .NET Standard 1.1.   I think instead, you should simply target 1.1 and nothing else extra.

Thoughts?

**Comment by Domysee** [comment]
Thanks for your analysis, I'll have a look at it in the next week and get back to you then.

**Comment by waynebrantley** [comment]
Thanks.  The way your library sits now...it only works on core...but if you add a 1.1 target also, then others can use it.

**Comment by Domysee** [comment]
Sorry for the delay, I had a look now. 
Although I couldn't exactly reproduce this issue as you described it, I was able to remove the reference to `System.Runtime.InteropServices` completely, and therefore stay on .NET Standard 1.0. 
The new version, 2.0.1, includes this change. 
It would be great if you can give me feedback if that resolved the issue.

**Comment by waynebrantley** [comment]
That sounds like it would take care of it.  I just think it was a problem because you targeted one platform and added a library from another platform that was causing issues.
