### ISSUE TITLE
Non-Enumerable class with Indexer

### ISSUE THREAD

**Issue by michal-ciechan** [Domysee/Pather.CSharp#2]
`NullReferenceException` happens if you try to Resolve a indexer path on an object which does not implement IEnumerable

Test code:

        public class IndexerClassNoIEnumerable
        {
            private readonly string value;

            public IndexerClassNoIEnumerable(string value)
            {
                this.value = value;
            }

            public string this[int index] => value + index;
        }

        [TestMethod]
        public void Resolver_IndexerClassNoIEnumerable_ThrowsException()
        {
            var target = new IndexerClassNoIEnumerable("Test");
            var resolver = new Resolver();
            var path = "[123456]";

            var res = resolver.Resolve(target, path);
            // throws 
            // System.NullReferenceException: Object reference not set to an instance of an object.
            // at Pather.CSharp.PathElements.EnumerableAccess.Apply(Object target)
            // at Pather.CSharp.Resolver.Resolve(Object target, IList`1 pathElements)
            // at Pather.CSharp.Resolver.Resolve(Object target, String path)

            res.Should().Be("Test123456");
        }

**Comment by michal-ciechan** [comment]
Will try to fix when I get home tonight

**Comment by Domysee** [comment]
Thank you for the detailed analysis. I have fixed that bug in version 2.0.2. 
The same bug happened also with string indexer, which is also fixed.
