### ISSUE TITLE
Does not get property of base class.

### ISSUE THREAD

**Issue by ms007** [Domysee/Pather.CSharp#4]
if the current class has an abstract base class, the property does not get resolved:

File: Property.cs
Line of Code: PropertyInfo p = target.GetType().GetTypeInfo().GetDeclaredProperty(property);

It will get resolved with 
PropertyInfo p = target.GetType().GetTypeInfo().GetProperty(property);

**Comment by Domysee** [comment]
Thank you for the report. 
I have fixed it with `target.GetType().GetRuntimeProperty(property);`, as `GetProperty` seems to not be available on `TypeInfo` in netstandard1.0.
The fix will be included in version 2.0.3.
