### ISSUE TITLE
Dealing with paths through nullable objects

### ISSUE THREAD

**Issue by statler** [Domysee/Pather.CSharp#5]
Inevitably, when using the path through an object, you come across the case where an object in the path is null. As expected this causes an exception. Is there any way to deal with this in a similar way to the c#6 syntax e.g. myproperty?.mySubproperty

Really handy little library by the way :)

**Comment by Domysee** [comment]
It would definitely be possible to support the same syntax as the null conditional operator in C#.  
Another way would be to add an extra method, `ResolveSafe`, which doesn't throw exceptions, but returns null. 

I'm not sure yet which the better option is, but this sure is a good feature to add.

**Comment by Domysee** [comment]
This is done now, in version 2.1.0, `Resolver` has a `ResolveSafe` method.
